// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0h3e_xER-V9CTSo66z3JV4u3Fd2NPRw',
    appId: '1:990501650932:web:0fbd1809c504f56d52f9a1',
    messagingSenderId: '990501650932',
    projectId: 'graduation-project-49e1d',
    authDomain: 'graduation-project-49e1d.firebaseapp.com',
    storageBucket: 'graduation-project-49e1d.appspot.com',
    measurementId: 'G-TLH4K9YGLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMLs-3dcO87BVyxJ_zPwT1EvOuz1hiq4U',
    appId: '1:990501650932:android:e78000920c76c1d252f9a1',
    messagingSenderId: '990501650932',
    projectId: 'graduation-project-49e1d',
    storageBucket: 'graduation-project-49e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6kXY7Z7hJwOky1vEXYRpZyLfLMTWw-o',
    appId: '1:990501650932:ios:3b7124c3c624c28c52f9a1',
    messagingSenderId: '990501650932',
    projectId: 'graduation-project-49e1d',
    storageBucket: 'graduation-project-49e1d.appspot.com',
    iosClientId: '990501650932-0jte4pq6qss5fske6sj5f9ip4q4t3251.apps.googleusercontent.com',
    iosBundleId: 'com.example.grduationProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6kXY7Z7hJwOky1vEXYRpZyLfLMTWw-o',
    appId: '1:990501650932:ios:3b7124c3c624c28c52f9a1',
    messagingSenderId: '990501650932',
    projectId: 'graduation-project-49e1d',
    storageBucket: 'graduation-project-49e1d.appspot.com',
    iosClientId: '990501650932-0jte4pq6qss5fske6sj5f9ip4q4t3251.apps.googleusercontent.com',
    iosBundleId: 'com.example.grduationProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI0h3e_xER-V9CTSo66z3JV4u3Fd2NPRw',
    appId: '1:990501650932:web:3d4857b057a99ff852f9a1',
    messagingSenderId: '990501650932',
    projectId: 'graduation-project-49e1d',
    authDomain: 'graduation-project-49e1d.firebaseapp.com',
    storageBucket: 'graduation-project-49e1d.appspot.com',
    measurementId: 'G-BJDXSN8KD7',
  );
}
